# 项目基本配置
project_name: ${PROJECT_NAME:pytest-auto-api2}

# 环境配置 - 支持多环境切换
# 可选值: test(测试环境), staging(预发环境), prod(生产环境)
env: ${TEST_ENV:test}
env_name: ${ENV_NAME:测试环境}

# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name: ${TESTER_NAME:txl}

# 多环境服务地址配置
environments:
  test:
    name: "测试环境"
    host: ${TEST_HOST:https://test-api.example.com}
    app_host: ${TEST_APP_HOST:}
    database_url: ${TEST_DB_URL:}
  staging:
    name: "预发环境"
    host: ${STAGING_HOST:https://staging-api.example.com}
    app_host: ${STAGING_APP_HOST:}
    database_url: ${STAGING_DB_URL:}
  prod:
    name: "生产环境"
    host: ${PROD_HOST:https://api.example.com}
    app_host: ${PROD_APP_HOST:}
    database_url: ${PROD_DB_URL:}

# 当前环境的服务地址（向后兼容）
host: ${HOST:https://www.wanandroid.com}
app_host: ${APP_HOST:}

# 测试用例配置
# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: ${REAL_TIME_UPDATE:False}

# 数据驱动配置
# 数据驱动类型：yaml 或 excel
data_driver_type: ${DATA_DRIVER_TYPE:yaml}
# YAML数据文件路径
yaml_data_path: ${YAML_DATA_PATH:data/yaml_data}
# Excel数据文件路径
excel_data_path: ${EXCEL_DATA_PATH:data/excel_data}

# 通知配置
# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
# 支持同时发送多个通知，如多个，则用逗号分割， 如 1, 2
notification_type: ${NOTIFICATION_TYPE:2}
# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
excel_report: ${EXCEL_REPORT:False}
# 增强通知格式开关：True使用增强格式（包含告警级别、趋势分析等），False使用原始格式
enhanced_notification: ${ENHANCED_NOTIFICATION:True}
# 生成默认报告开关：True同时生成默认html目录（向后兼容），False只生成带时间戳的报告
generate_default_report: ${GENERATE_DEFAULT_REPORT:True}

# 注意点：
# 之前为了小伙伴们拉下代码执行的时候不受影响，企业微信、钉钉、邮箱的通知配置的都是我的
# 我发现很多拉代码的小伙伴这里配置都没改，所有的通知都发到我这里来了哦~~麻烦看到这里的小伙伴自己改一下相关配置

# 钉钉通知配置
ding_talk:
  webhook: ${DING_TALK_WEBHOOK:}
  secret: ${DING_TALK_SECRET:}

# 数据库配置
mysql_db:
  # 数据库开关
  switch: ${MYSQL_SWITCH:False}
  host: ${MYSQL_HOST:localhost}
  user: ${MYSQL_USER:root}
  password: ${MYSQL_PASSWORD:"123456"}
  port: ${MYSQL_PORT:3306}
  database: ${MYSQL_DATABASE:test}

# Python包镜像源配置
mirror_source: ${MIRROR_SOURCE:http://mirrors.aliyun.com/pypi/simple/}

# 企业微信通知配置
wechat:
  webhook: ${WECHAT_WEBHOOK:https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=8fc9dc42-b9fa-4dcf-ab72-1c0ebb2da76c}

# 邮箱通知配置
# 注意：邮箱配置为必填项，程序运行失败时会发送邮件通知
email:
  send_user: ${EMAIL_SEND_USER:}
  email_host: ${EMAIL_HOST:smtp.qq.com}
  # QQ邮箱授权码，需要在QQ邮箱中开启SMTP服务并获取授权码
  stamp_key: ${EMAIL_STAMP_KEY:}
  # 收件人邮箱列表，多个邮箱用逗号分隔
  send_list: ${EMAIL_SEND_LIST:}

# 飞书通知配置
lark:
  webhook: ${LARK_WEBHOOK:}



